import type { InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getAllPosts } from "../lib/api";

type Props = InferGetStaticPropsType<typeof getStaticProps>;

export const getStaticProps = async () => {
  const allPosts = getAllPosts(["slug", "title", "date", "tags"]);
  return {
    props: { allPosts },
  };
};

const Home: NextPage<Props> = ({ allPosts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>TopPage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to my page！</h1>
        <div>Hi there! I'm Kenta Kakimoto, a dedicated and versatile engineer specializing in full-stack development. With a strong foundation in programming languages, I thrive on creating efficient, scalable, and user-friendly solutions.<br/>
            Over three years, I have honed my skills through various projects, allowing me to adapt and grow continuously. My passion for technology drives me to stay updated with the latest trends and innovations, ensuring that I bring the best practices to every project I undertake.
        </div>
        <div className={styles.grid}>
          {allPosts.map((post) => (
            <div>
              <a href={post.slug} className={styles.card} key={post.slug}>
                {post.title}
              </a>
            </div>
          ))}
        </div>
      </main>
      <footer className={styles.footer}>
        <p>Powered by Next.js.</p>
      </footer>
    </div>
  );
};

export default Home;